// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include "../serial_port.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

app_context_t app_ctx = {
    .is_inside_mode = true, // Default to inside mode
    .inside_humidity = 70,
    .outside_humidity = 90,
    .inside_temperature = 23,
    .outside_temperature = 28
};

static int s_serial_fd = -1;

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

static void serial_data_cb(const uint8_t *data, size_t len)
{
    // serial_write(s_serial_fd, "1234", strlen("1234"));

    if (!data || len <= 0)
        return;

    app_ctx.inside_humidity = data[0] << 8 | data[1];
}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // static bool ui_init_done = false;
    // if (ui_init_done)
    // {
    //     ui_draw_cur_screen();
    //     return;
    // }
    // ui_init_done = true;

    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    ui_draw_cur_screen();

    // ---- Serial example: open /dev/ttyS1 and start reader ----
    
    s_serial_fd = serial_open("/dev/ttyS1", 115200);
    if (s_serial_fd >= 0)
    {
        const char *test = "rv app version 1.0\n";
        serial_write(s_serial_fd, test, strlen(test));
        serial_start_reader(s_serial_fd, serial_data_cb);
    }    
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
    ui_Screen4_screen_destroy();
    ui_Screen5_screen_destroy();
    ui_Screen6_screen_destroy();
    ui_Screen7_screen_destroy();
    ui_Screen8_screen_destroy();
}

void ui_relocalize(void)
{
    ui_Screen1_screen_relocalize();
    ui_Screen2_screen_relocalize();
    ui_Screen3_screen_relocalize();
    ui_Screen4_screen_relocalize();
    ui_Screen5_screen_relocalize();
    ui_Screen6_screen_relocalize();
    ui_Screen7_screen_relocalize();
    ui_Screen8_screen_relocalize();
}
