// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

//#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen7.h"
#include "screens/ui_Screen8.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_homepage_png);    // assets/homepage.png
LV_IMG_DECLARE(ui_img_charger_png);    // assets/charger.png
LV_IMG_DECLARE(ui_img_water_box_png);    // assets/water_box.png
LV_IMG_DECLARE(ui_img_device_png);    // assets/device.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_camera_png);    // assets/camera.png
LV_IMG_DECLARE(ui_img_balance_png);    // assets/balance.png
LV_IMG_DECLARE(ui_img_switch_on_png);    // switch ON state
LV_IMG_DECLARE(ui_img_switch_off_png);    // switch OFF state
LV_IMG_DECLARE(ui_img_homepage_unsel_png);    // assets/homepage_unsel.png
LV_IMG_DECLARE(ui_img_charger_unsel_png);    // assets/charger_unsel.png
LV_IMG_DECLARE(ui_img_water_box_unsel_png);    // assets/water_box_unsel.png
LV_IMG_DECLARE(ui_img_device_unsel_png);    // assets/device_unsel.png
LV_IMG_DECLARE(ui_img_light_unsel_png);    // assets/light_unsel.png
LV_IMG_DECLARE(ui_img_setting_unsel_png);    // assets/setting_unsel.png
LV_IMG_DECLARE(ui_img_camera_unsel_png);    // assets/camera_unsel.png
LV_IMG_DECLARE(ui_img_balance_unsel_png);    // assets/balance_unsel.png
LV_IMG_DECLARE(ui_img_homepage_sel_png);    // assets/homepage_sel.png
LV_IMG_DECLARE(ui_img_charger_sel_png);    // assets/charger_sel.png
LV_IMG_DECLARE(ui_img_water_box_sel_png);    // assets/water_box_sel.png
LV_IMG_DECLARE(ui_img_device_sel_png);    // assets/device_sel.png
LV_IMG_DECLARE(ui_img_light_sel_png);    // assets/light_sel.png
LV_IMG_DECLARE(ui_img_setting_sel_png);    // assets/setting_sel.png
LV_IMG_DECLARE(ui_img_camera_sel_png);    // assets/camera_sel.png
LV_IMG_DECLARE(ui_img_balance_sel_png);    // assets/balance_sel.png    
LV_IMG_DECLARE(ui_img_inside_unsel_png);
LV_IMG_DECLARE(ui_img_inside_sel_png);
LV_IMG_DECLARE(ui_img_outside_sel_png);
LV_IMG_DECLARE(ui_img_outside_unsel_png);
LV_IMG_DECLARE(ui_img_temp_icon_png);
LV_IMG_DECLARE(ui_img_humidity_icon_png);



LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Number_digital7);

#define NAV_ICON_NUM 8
#define SCREEN_DISPLAY_WIDTH 1920
#define SCREEN_DISPLAY_HEIGHT 1200

// 各种控件的颜色定义
#define COLOR_BG_DARK lv_color_hex(0x0)
#define COLOR_LABLE_WHITE lv_color_hex(0xFFFFFF)
#define COLOR_LABLE_GRAY lv_color_hex(0x888888)
#define COLOR_HIGHLIGHT lv_color_hex(0x189FBF)
#define COLOR_NORMAL lv_color_hex(0x141432)

typedef struct {
    bool is_inside_mode; // true for inside, false for outside
    int16_t inside_temperature;
    int16_t outside_temperature;
    uint16_t inside_humidity;
    uint16_t outside_humidity;
    uint8_t camera_id; // 当前使用的摄像头ID
} app_context_t;

extern app_context_t app_ctx;

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

void ui_draw_navigation_bar(lv_obj_t * parent);
void ui_navigation_bar_destroy(void);
lv_obj_t *ui_create_display_container(lv_obj_t *parent, lv_color_t bg_color, uint16_t x, uint16_t y, uint16_t width, uint16_t height);
void ui_draw_cur_screen(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
