// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Imagecharger = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // 获取屏幕坐标,如果点击不在矩形范围内,则不处理 
    lv_obj_t * cont = lv_event_get_target(e);
    lv_indev_t * indev = lv_indev_get_act(); // 获取输入设备
    if (indev == NULL) return;
    
    lv_point_t point;
    lv_indev_get_point(indev, &point); // 获取触摸点坐标
    if(point.x < 1920 / 8 * 0 || point.x > 1920 / 8 * 0 + 1920 / 8 || point.y < 980 || point.y > 1199) {
        return;
    }

    if(event_code == LV_EVENT_CLICKED) {
        

        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagecharger = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Imagecharger, &ui_img_charger_png);
    lv_obj_set_width(ui_Imagecharger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Imagecharger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Imagecharger, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Imagecharger, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagecharger, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Imagecharger = NULL;

}

void ui_Screen2_screen_relocalize(void)
{
    // label widgets on screen

}
