// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;

static lv_obj_t * ui_Image_balance = NULL;

extern void _ui_common_screen_change(uint16_t cur_screen_id, lv_event_t * e);

// event funtions
void ui_event_Screen5(lv_event_t * e)
{
    _ui_common_screen_change(4, e);
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_balance = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image_balance, &ui_img_balance_png);
    lv_obj_set_width(ui_Image_balance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_balance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_balance, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_balance, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_balance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Image_balance = NULL;

}

void ui_Screen5_screen_relocalize(void)
{
    // label widgets on screen

}
