// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;

static lv_obj_t * ui_Imagewater_box = NULL;

extern void _ui_common_screen_change(uint16_t cur_screen_id, lv_event_t * e);

// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    _ui_common_screen_change(2, e);
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagewater_box = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Imagewater_box, &ui_img_water_box_png);
    lv_obj_set_width(ui_Imagewater_box, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Imagewater_box, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Imagewater_box, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Imagewater_box, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagewater_box, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Imagewater_box = NULL;

}

void ui_Screen3_screen_relocalize(void)
{
    // label widgets on screen

}
