// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen6 = NULL;

static lv_obj_t * ui_Image_device = NULL;

extern void _ui_common_screen_change(uint16_t cur_screen_id, lv_event_t * e);

// event funtions
void ui_event_Screen6(lv_event_t * e)
{
    _ui_common_screen_change(5, e);
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_device = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image_device, &ui_img_device_png);
    lv_obj_set_width(ui_Image_device, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_device, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_device, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_device, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_device, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Image_device = NULL;

}

void ui_Screen6_screen_relocalize(void)
{
    // label widgets on screen

}
