// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;

static lv_obj_t * ui_Image_balance = NULL;

extern void _ui_common_screen_change(uint16_t cur_screen_id, lv_event_t * e);

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // 设置背景色为深蓝色
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_Screen5, 1920, 1200);    

    ui_Image_balance = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image_balance, &ui_img_balance_png);
    lv_obj_set_width(ui_Image_balance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_balance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_balance, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image_balance, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_balance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_draw_navigation_bar(ui_Screen5);
}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Image_balance = NULL;
    ui_navigation_bar_destroy();

}

void ui_Screen5_screen_relocalize(void)
{
    // label widgets on screen

}
