// This file was generated by SquareLine Studio
// WiFi 设置界面：开关、已连接、可用列表、信号强度、连接/断开

#include "../ui.h"
#include "../wifi_utils.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

lv_obj_t * ui_Screen4 = NULL;

static lv_obj_t * ui_switch_wifi = NULL;
static lv_obj_t * ui_label_wifi_title = NULL;
static lv_obj_t * ui_cont_wifi_content = NULL;
static lv_obj_t * ui_label_connected_title = NULL;
static lv_obj_t * ui_cont_connected = NULL;
static lv_obj_t * ui_label_connected_ssid = NULL;
static lv_obj_t * ui_label_available_title = NULL;
static lv_obj_t * ui_btn_scan = NULL;
static lv_obj_t * ui_list_available = NULL;
static lv_timer_t * ui_wifi_timer = NULL;
static lv_obj_t * ui_overlay_connected_row = NULL;

#define ROW_H            56
#define LIST_MAX         32
#define WIFI_PANEL_W     800
#define WIFI_PANEL_X     60
#define WIFI_TOP_Y       80
#define WIFI_POLL_MS     800
#define WIFI_PWD_PANEL_W 520
#define WIFI_PWD_PANEL_H 280
#define WIFI_MENU_BTN_W  160
#define WIFI_MENU_BTN_H  48
#define PWD_PANEL_CHILD_TA 1

typedef struct {
    char ssid[WIFI_UTILS_SSID_MAX_LEN];
    int  secured;
} wifi_row_data_t;

extern void _ui_common_screen_change(uint16_t cur_screen_id, lv_event_t * e);

static void wifi_list_cleanup_user_data(lv_obj_t * list);
static void wifi_available_row_click_cb(lv_event_t * e);
static void wifi_show_password_dialog(const char * ssid);

/* 根据 RSSI 返回 1~4 格信号等级，或 0 表示未知 */
static int rssi_to_bars(int rssi) {
    if (rssi >= -50) return 4;
    if (rssi >= -60) return 3;
    if (rssi >= -70) return 2;
    if (rssi >= -100) return 1;
    return 0;
}

static bool wifi_ui_is_enabled(void)
{
    if (ui_switch_wifi) return lv_obj_has_state(ui_switch_wifi, LV_STATE_CHECKED);
    return is_wifi_enabled();
}

/* Connected 行在 Screen4 上的区域：与 ui_cont_wifi_content 内 (0,40) 行对应 */
#define CONNECTED_ROW_SCREEN_X   (WIFI_PANEL_X)
#define CONNECTED_ROW_SCREEN_Y   (WIFI_TOP_Y + 60 + 40)

/* Show or hide Connected + Available block (single container) according to WiFi on/off */
static void wifi_show_hide_connected_and_available(void) {
    if (!ui_cont_wifi_content) return;
    if (!wifi_ui_is_enabled()) {
        lv_obj_add_flag(ui_cont_wifi_content, LV_OBJ_FLAG_HIDDEN);
        if (ui_overlay_connected_row) lv_obj_add_flag(ui_overlay_connected_row, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(ui_cont_wifi_content, LV_OBJ_FLAG_HIDDEN);
        if (ui_overlay_connected_row) lv_obj_clear_flag(ui_overlay_connected_row, LV_OBJ_FLAG_HIDDEN);
    }
    if (ui_Screen4)
        lv_obj_invalidate(ui_Screen4);
}

static void wifi_refresh_connected_row(void) {
    if (!ui_label_connected_ssid) return;
    char ssid[WIFI_UTILS_SSID_MAX_LEN];
    if (!wifi_ui_is_enabled()) {
        lv_label_set_text(ui_label_connected_ssid, "WiFi is off");
        wifi_show_hide_connected_and_available();
        return;
    }
    wifi_show_hide_connected_and_available();
    if (get_display_connected_ssid(ssid, sizeof(ssid)) && ssid[0] != '\0') {
        lv_label_set_text(ui_label_connected_ssid, ssid);
        lv_obj_set_style_text_color(ui_label_connected_ssid, COLOR_LABLE_WHITE, LV_PART_MAIN);
    } else {
        lv_label_set_text(ui_label_connected_ssid, "Not connected");
        lv_obj_set_style_text_color(ui_label_connected_ssid, COLOR_LABLE_GRAY, LV_PART_MAIN);
    }
}

static void wifi_show_list_placeholder(const char * text) {
    if (!ui_list_available) return;
    wifi_list_cleanup_user_data(ui_list_available);
    lv_obj_clean(ui_list_available);
    lv_obj_t * row = lv_obj_create(ui_list_available);
    lv_obj_set_size(row, lv_obj_get_width(ui_list_available) - 24, ROW_H - 4);
    lv_obj_set_style_bg_color(row, COLOR_NORMAL, LV_PART_MAIN);
    lv_obj_set_style_radius(row, 8, LV_PART_MAIN);
    lv_obj_set_style_border_width(row, 0, LV_PART_MAIN);
    lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_t * lab = lv_label_create(row);
    lv_label_set_text(lab, text);
    lv_obj_set_style_text_color(lab, COLOR_LABLE_GRAY, LV_PART_MAIN);
    lv_obj_set_style_text_font(lab, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_center(lab);
}

static void wifi_refresh_available_list(void) {
    wifi_utils_scan_entry_t entries[WIFI_UTILS_SCAN_MAX];
    int n = wifi_utils_consume_scan_results(entries, WIFI_UTILS_SCAN_MAX);
    if (n < 0) return;  /* no new scan result */

    wifi_list_cleanup_user_data(ui_list_available);
    lv_obj_clean(ui_list_available);
    if (n == 0) {
        wifi_show_list_placeholder("No networks found");
        return;
    }

    char connected_ssid[WIFI_UTILS_SSID_MAX_LEN];
    bool has_connected = get_display_connected_ssid(connected_ssid, sizeof(connected_ssid)) && connected_ssid[0] != '\0';

    int shown = 0;
    for (int i = 0; i < n && shown < LIST_MAX; i++) {
        if (has_connected && strcmp(entries[i].ssid, connected_ssid) == 0)
            continue;
        shown++;

        lv_obj_t * row = lv_obj_create(ui_list_available);
        lv_obj_set_size(row, lv_obj_get_width(ui_list_available) - 24, ROW_H - 4);
        lv_obj_set_style_bg_color(row, COLOR_NORMAL, LV_PART_MAIN);
        lv_obj_set_style_bg_opa(row, LV_OPA_COVER, LV_PART_MAIN);
        lv_obj_set_style_radius(row, 8, LV_PART_MAIN);
        lv_obj_set_style_border_width(row, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(row, 8, LV_PART_MAIN);
        lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_add_flag(row, LV_OBJ_FLAG_CLICKABLE);

        lv_obj_t * lab = lv_label_create(row);
        lv_label_set_text(lab, entries[i].ssid[0] ? entries[i].ssid : "(Hidden network)");
        lv_obj_set_style_text_color(lab, COLOR_LABLE_WHITE, LV_PART_MAIN);
        lv_obj_set_style_text_font(lab, &lv_font_montserrat_28, LV_PART_MAIN);
        lv_obj_align(lab, LV_ALIGN_LEFT_MID, 8, 0);

        int bars = rssi_to_bars(entries[i].rssi);
        char sig[16];
        if (bars > 0) {
            snprintf(sig, sizeof(sig), "%d bars", bars);
        } else {
            snprintf(sig, sizeof(sig), "%d", entries[i].rssi);
        }
        lv_obj_t * sig_lab = lv_label_create(row);
        lv_label_set_text(sig_lab, sig);
        lv_obj_set_style_text_color(sig_lab, COLOR_LABLE_GRAY, LV_PART_MAIN);
        lv_obj_set_style_text_font(sig_lab, &lv_font_montserrat_24, LV_PART_MAIN);
        lv_obj_align(sig_lab, LV_ALIGN_RIGHT_MID, -12, 0);

        /* 将 SSID + secured 存到 row 的 user_data */
        wifi_row_data_t * row_data = (wifi_row_data_t *)malloc(sizeof(wifi_row_data_t));
        if (row_data) {
            strncpy(row_data->ssid, entries[i].ssid, WIFI_UTILS_SSID_MAX_LEN - 1);
            row_data->ssid[WIFI_UTILS_SSID_MAX_LEN - 1] = '\0';
            row_data->secured = entries[i].secured;
            lv_obj_set_user_data(row, row_data);
        }
        lv_obj_add_event_cb(row, wifi_available_row_click_cb, LV_EVENT_CLICKED, NULL);
    }
    if (shown == 0)
        wifi_show_list_placeholder("No networks found");
}

static void wifi_apply_connect_result(void) {
    int r = wifi_utils_consume_connect_result();
    if (r == 0) return;
    wifi_refresh_connected_row();
    (void)r; /* 可在此根据 r==1/-1 显示提示 */
}

static void wifi_timer_cb(lv_timer_t * t) {
    (void)t;
    wifi_refresh_available_list();
    wifi_apply_connect_result();
    wifi_refresh_connected_row();
}

static void wifi_switch_event_cb(lv_event_t * e) {
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED) return;
    lv_obj_t * sw = lv_event_get_target(e);
    bool on = lv_obj_has_state(sw, LV_STATE_CHECKED);
    set_wifi_enabled(on);
    wifi_show_hide_connected_and_available();
    wifi_refresh_connected_row();
    if (on) {
        wifi_show_list_placeholder("Scanning...");
        scan_wifi_networks();
    }
}

static void wifi_scan_btn_cb(lv_event_t * e) {
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    if (!wifi_ui_is_enabled()) return;
    wifi_show_list_placeholder("Scanning...");
    scan_wifi_networks();
}

/* 从事件目标（按钮或按钮内 label）找到密码弹窗的 panel（user_data 存 ssid） */
static lv_obj_t * wifi_pwd_get_panel_from_target(lv_obj_t * target) {
    lv_obj_t * panel = lv_obj_get_parent(target);
    if (!panel || !lv_obj_get_user_data(panel))
        panel = lv_obj_get_parent(panel);
    return panel;
}

/* 关闭密码弹窗并释放 panel 的 ssid；overlay 为弹窗根容器 */
static void wifi_pwd_close_and_free(lv_obj_t * overlay) {
    lv_obj_t * panel = lv_obj_get_child(overlay, 0);
    if (panel) {
        char * ssid = (char *)lv_obj_get_user_data(panel);
        if (ssid) free(ssid);
    }
    lv_obj_del(overlay);
}

static void wifi_pwd_connect_btn_cb(lv_event_t * e) {
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t * panel = wifi_pwd_get_panel_from_target(target);
    lv_obj_t * overlay = panel ? lv_obj_get_parent(panel) : NULL;
    if (!panel || !overlay) return;
    char * ssid = (char *)lv_obj_get_user_data(panel);
    lv_obj_t * ta = lv_obj_get_child(panel, PWD_PANEL_CHILD_TA);
    const char * pwd = ta ? lv_textarea_get_text(ta) : "";
    if (ssid) {
        connect_to_wifi(ssid, pwd ? pwd : "", NULL);
        free(ssid);
    }
    lv_obj_set_user_data(panel, NULL);
    lv_obj_del(overlay);
}

static void wifi_pwd_cancel_btn_cb(lv_event_t * e) {
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    lv_obj_t * panel = wifi_pwd_get_panel_from_target(lv_event_get_target(e));
    if (panel) wifi_pwd_close_and_free(lv_obj_get_parent(panel));
}

static void wifi_pwd_overlay_click_cb(lv_event_t * e) {
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    wifi_pwd_close_and_free(lv_event_get_target(e));
}

static void wifi_show_password_dialog(const char * ssid) {
    if (!ssid || !ui_Screen4 || !wifi_ui_is_enabled()) return;
    char * ssid_copy = (char *)malloc(WIFI_UTILS_SSID_MAX_LEN);
    if (!ssid_copy) return;
    strncpy(ssid_copy, ssid, WIFI_UTILS_SSID_MAX_LEN - 1);
    ssid_copy[WIFI_UTILS_SSID_MAX_LEN - 1] = '\0';

    lv_obj_t * overlay = lv_obj_create(ui_Screen4);
    lv_obj_set_size(overlay, lv_obj_get_width(ui_Screen4), lv_obj_get_height(ui_Screen4));
    lv_obj_set_pos(overlay, 0, 0);
    lv_obj_set_style_bg_color(overlay, lv_color_hex(0x0), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(overlay, LV_OPA_70, LV_PART_MAIN);
    lv_obj_clear_flag(overlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(overlay, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(overlay, wifi_pwd_overlay_click_cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t * panel = lv_obj_create(overlay);
    lv_obj_set_size(panel, WIFI_PWD_PANEL_W, WIFI_PWD_PANEL_H);
    lv_obj_center(panel);
    lv_obj_set_style_bg_color(panel, COLOR_NORMAL, LV_PART_MAIN);
    lv_obj_set_style_radius(panel, 16, LV_PART_MAIN);
    lv_obj_set_style_border_width(panel, 0, LV_PART_MAIN);
    lv_obj_clear_flag(panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_user_data(panel, ssid_copy);

    static char title_buf[128];
    snprintf(title_buf, sizeof(title_buf), "Password for %s", ssid_copy[0] ? ssid_copy : "(Hidden)");
    lv_obj_t * lab = lv_label_create(panel);
    lv_label_set_text(lab, title_buf);
    lv_obj_set_style_text_color(lab, COLOR_LABLE_WHITE, LV_PART_MAIN);
    lv_obj_set_style_text_font(lab, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_align(lab, LV_ALIGN_TOP_MID, 0, 16);

    lv_obj_t * ta = lv_textarea_create(panel);
    lv_obj_set_size(ta, WIFI_PWD_PANEL_W - 48, 52);
    lv_obj_align(ta, LV_ALIGN_TOP_MID, 0, 56);
    lv_textarea_set_one_line(ta, true);
    lv_textarea_set_max_length(ta, 63);
    lv_textarea_set_placeholder_text(ta, "Password");
    lv_textarea_set_password_mode(ta, true);
    lv_obj_set_style_text_font(ta, &lv_font_montserrat_24, LV_PART_MAIN);

    /* 虚拟键盘：与密码框绑定，弹窗出现时同时显示 */
    lv_obj_t * kb = lv_keyboard_create(overlay);
    lv_keyboard_set_textarea(kb, ta);
    lv_obj_set_style_bg_color(kb, COLOR_NORMAL, LV_PART_MAIN);
    lv_obj_set_size(kb, lv_obj_get_width(ui_Screen4), 280);
    lv_obj_align(kb, LV_ALIGN_BOTTOM_MID, 0, 0);

    lv_obj_t * btn_connect = lv_btn_create(panel);
    lv_obj_set_size(btn_connect, WIFI_MENU_BTN_W, WIFI_MENU_BTN_H);
    lv_obj_set_style_bg_color(btn_connect, COLOR_HIGHLIGHT, LV_PART_MAIN);
    lv_obj_t * lbl_conn = lv_label_create(btn_connect);
    lv_label_set_text(lbl_conn, "Connect");
    lv_obj_center(lbl_conn);
    lv_obj_add_event_cb(btn_connect, wifi_pwd_connect_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_align(btn_connect, LV_ALIGN_BOTTOM_LEFT, 40, -24);

    lv_obj_t * btn_cancel = lv_btn_create(panel);
    lv_obj_set_size(btn_cancel, WIFI_MENU_BTN_W, WIFI_MENU_BTN_H);
    lv_obj_set_style_bg_color(btn_cancel, COLOR_LABLE_GRAY, LV_PART_MAIN);
    lv_obj_t * lbl_cancel = lv_label_create(btn_cancel);
    lv_label_set_text(lbl_cancel, "Cancel");
    lv_obj_center(lbl_cancel);
    lv_obj_add_event_cb(btn_cancel, wifi_pwd_cancel_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_align(btn_cancel, LV_ALIGN_BOTTOM_RIGHT, -40, -24);
}

static void wifi_available_row_click_cb(lv_event_t * e) {
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    lv_obj_t * row = lv_event_get_target(e);
    wifi_row_data_t * row_data = (wifi_row_data_t *)lv_obj_get_user_data(row);
    if (!row_data || !wifi_ui_is_enabled()) return;
    if (row_data->secured)
        wifi_show_password_dialog(row_data->ssid);
    else
        connect_to_wifi(row_data->ssid, "", NULL);
}

static void wifi_connected_row_click_cb(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    /* 同时响应 PRESSED 与 CLICKED，提高触摸屏上触发的可靠性 */
    if (code != LV_EVENT_CLICKED && code != LV_EVENT_PRESSED) return;
    char ssid[WIFI_UTILS_SSID_MAX_LEN];
    if (!get_display_connected_ssid(ssid, sizeof(ssid)) || ssid[0] == '\0') return;
    wifi_utils_clear_last_success_ssid();
    disconnect_wifi();
    /* 立即把界面置为“未连接”：Android disconnect() 是异步的 */
    lv_label_set_text(ui_label_connected_ssid, "Not connected");
    lv_obj_set_style_text_color(ui_label_connected_ssid, COLOR_LABLE_GRAY, LV_PART_MAIN);
    /* 定时器会继续轮询 wifi_refresh_connected_row()，稍后与真实状态同步 */
}

static void wifi_list_cleanup_user_data(lv_obj_t * list) {
    int cnt = lv_obj_get_child_cnt(list);
    for (int i = 0; i < cnt; i++) {
        lv_obj_t * child = lv_obj_get_child(list, i);
        wifi_row_data_t * p = (wifi_row_data_t *)lv_obj_get_user_data(child);
        if (p) { free(p); lv_obj_set_user_data(child, NULL); }
    }
}

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_Screen4, 1920, 1200);

    // ui_Image_setting = lv_img_create(ui_Screen4);
    // lv_img_set_src(ui_Image_setting, &ui_img_setting_png);
    // lv_obj_set_width(ui_Image_setting, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_Image_setting, LV_SIZE_CONTENT);
    // lv_obj_set_align(ui_Image_setting, LV_ALIGN_TOP_LEFT);
    // lv_obj_add_flag(ui_Image_setting, LV_OBJ_FLAG_ADV_HITTEST);
    // lv_obj_clear_flag(ui_Image_setting, LV_OBJ_FLAG_SCROLLABLE);

    /* 标题 */
    ui_label_wifi_title = lv_label_create(ui_Screen4);
    lv_label_set_text(ui_label_wifi_title, "WiFi");
    lv_obj_set_style_text_color(ui_label_wifi_title, COLOR_LABLE_WHITE, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_label_wifi_title, &lv_font_montserrat_36, LV_PART_MAIN);
    lv_obj_set_pos(ui_label_wifi_title, WIFI_PANEL_X, WIFI_TOP_Y - 10);

    /* WiFi 开关 */
    ui_switch_wifi = lv_switch_create(ui_Screen4);
    lv_obj_set_size(ui_switch_wifi, 120, 56);
    lv_obj_set_pos(ui_switch_wifi, WIFI_PANEL_X + 120, WIFI_TOP_Y - 8);
    lv_obj_add_event_cb(ui_switch_wifi, wifi_switch_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    if (is_wifi_enabled())
        lv_obj_add_state(ui_switch_wifi, LV_STATE_CHECKED);

    /* 父容器：WiFi 关闭时整体隐藏，内部为 Connected + Available 区域 */
    ui_cont_wifi_content = lv_obj_create(ui_Screen4);
    lv_obj_set_size(ui_cont_wifi_content, WIFI_PANEL_W, 592);
    lv_obj_set_pos(ui_cont_wifi_content, WIFI_PANEL_X, WIFI_TOP_Y + 60);
    lv_obj_set_style_bg_opa(ui_cont_wifi_content, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_cont_wifi_content, 0, LV_PART_MAIN);
    lv_obj_clear_flag(ui_cont_wifi_content, LV_OBJ_FLAG_SCROLLABLE);

    /* 已连接 标题 */
    ui_label_connected_title = lv_label_create(ui_cont_wifi_content);
    lv_label_set_text(ui_label_connected_title, "Connected");
    lv_obj_set_style_text_color(ui_label_connected_title, COLOR_LABLE_GRAY, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_label_connected_title, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_set_pos(ui_label_connected_title, 0, 0);

    /* 已连接 一行（可点击断开） */
    ui_cont_connected = lv_obj_create(ui_cont_wifi_content);
    lv_obj_set_size(ui_cont_connected, WIFI_PANEL_W, ROW_H);
    lv_obj_set_pos(ui_cont_connected, 0, 40);
    lv_obj_set_style_bg_color(ui_cont_connected, COLOR_NORMAL, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_cont_connected, 12, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_cont_connected, 0, LV_PART_MAIN);
    lv_obj_clear_flag(ui_cont_connected, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_cont_connected, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_cont_connected, wifi_connected_row_click_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_cont_connected, wifi_connected_row_click_cb, LV_EVENT_PRESSED, NULL);

    ui_label_connected_ssid = lv_label_create(ui_cont_connected);
    lv_label_set_text(ui_label_connected_ssid, "");
    lv_obj_set_style_text_color(ui_label_connected_ssid, COLOR_LABLE_WHITE, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_label_connected_ssid, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_align(ui_label_connected_ssid, LV_ALIGN_LEFT_MID, 16, 0);
    /* 不设 CLICKABLE，使整行点击都命中父容器 ui_cont_connected，由容器统一处理 */
    lv_obj_clear_flag(ui_label_connected_ssid, LV_OBJ_FLAG_CLICKABLE);

    /* 可用网络 标题 + 刷新按钮 */
    ui_label_available_title = lv_label_create(ui_cont_wifi_content);
    lv_label_set_text(ui_label_available_title, "Available networks");
    lv_obj_set_style_text_color(ui_label_available_title, COLOR_LABLE_GRAY, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_label_available_title, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_set_pos(ui_label_available_title, 0, 120);

    ui_btn_scan = lv_btn_create(ui_cont_wifi_content);
    lv_obj_set_size(ui_btn_scan, 140, 48);
    lv_obj_set_pos(ui_btn_scan, 200, 112);
    lv_obj_set_style_bg_color(ui_btn_scan, COLOR_HIGHLIGHT, LV_PART_MAIN);
    lv_obj_t * btn_lab = lv_label_create(ui_btn_scan);
    lv_label_set_text(btn_lab, "Refresh");
    lv_obj_center(btn_lab);
    lv_obj_add_event_cb(ui_btn_scan, wifi_scan_btn_cb, LV_EVENT_CLICKED, NULL);

    /* 可用网络列表（可滚动） */
    ui_list_available = lv_obj_create(ui_cont_wifi_content);
    lv_obj_set_size(ui_list_available, WIFI_PANEL_W, 420);
    lv_obj_set_pos(ui_list_available, 0, 172);
    lv_obj_set_style_bg_color(ui_list_available, lv_color_hex(0x0), LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_list_available, 0, LV_PART_MAIN);
    lv_obj_set_flex_flow(ui_list_available, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(ui_list_available, 6, LV_PART_MAIN);
    lv_obj_set_style_pad_column(ui_list_available, 0, LV_PART_MAIN);
    lv_obj_add_flag(ui_list_available, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(ui_list_available, LV_SCROLLBAR_MODE_AUTO);

    wifi_show_hide_connected_and_available();
    wifi_refresh_connected_row();
    if (wifi_ui_is_enabled()) {
        wifi_show_list_placeholder("Scanning...");
        scan_wifi_networks();
    }

    if (!ui_wifi_timer)
        ui_wifi_timer = lv_timer_create(wifi_timer_cb, WIFI_POLL_MS, NULL);
    lv_timer_resume(ui_wifi_timer);

    ui_draw_navigation_bar(ui_Screen4);

    /* 顶层透明覆盖层：仅覆盖 Connected 行，作为最后子控件优先接收点击（解决整行无反应） */
    ui_overlay_connected_row = lv_obj_create(ui_Screen4);
    lv_obj_set_size(ui_overlay_connected_row, WIFI_PANEL_W, ROW_H);
    lv_obj_set_pos(ui_overlay_connected_row, CONNECTED_ROW_SCREEN_X, CONNECTED_ROW_SCREEN_Y);
    lv_obj_set_style_bg_opa(ui_overlay_connected_row, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_overlay_connected_row, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(ui_overlay_connected_row, 0, LV_PART_MAIN);
    lv_obj_clear_flag(ui_overlay_connected_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_overlay_connected_row, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_overlay_connected_row, wifi_connected_row_click_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_overlay_connected_row, wifi_connected_row_click_cb, LV_EVENT_PRESSED, NULL);
    if (!wifi_ui_is_enabled())
        lv_obj_add_flag(ui_overlay_connected_row, LV_OBJ_FLAG_HIDDEN);
}

void ui_Screen4_screen_destroy(void)
{
    if (ui_wifi_timer) {
        lv_timer_del(ui_wifi_timer);
        ui_wifi_timer = NULL;
    }
    if (ui_list_available)
        wifi_list_cleanup_user_data(ui_list_available);
    if (ui_Screen4)
        lv_obj_del(ui_Screen4);

    ui_Screen4 = NULL;
    ui_switch_wifi = NULL;
    ui_label_wifi_title = NULL;
    ui_cont_wifi_content = NULL;
    ui_label_connected_title = NULL;
    ui_cont_connected = NULL;
    ui_label_connected_ssid = NULL;
    ui_overlay_connected_row = NULL;
    ui_label_available_title = NULL;
    ui_btn_scan = NULL;
    ui_list_available = NULL;
    ui_navigation_bar_destroy();
}

void ui_Screen4_screen_relocalize(void)
{
}

void ui_Screen4_refresh_wifi_connected_row(void)
{
    if (ui_label_connected_ssid)
        wifi_refresh_connected_row();
}
