// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern void ui_Screen8_screen_relocalize(void);
extern void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

